train:
  epochs: 1
  learning_rate: 0.01
  batch_size: 1
  num_workers: 0
  save_freq: 100
  checkpoint_dir: "checkpoints"
  log_freq: 1000
  
test:
  batch_size: 1
  num_workers: 0


nodes:
  hidden_dim: 64

leaves: 
  hidden_dim: 64

input_dim: 784
device: 'cpu'
feature_dim: 64
num_leaves: 4
num_classes: 10

